//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOneFinancialManagerMK2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public int Id { get; set; }
        public int AccountOwnerID { get; set; }
        public string AccountType { get; set; }
        public Nullable<double> Balance { get; set; }
        public Nullable<double> SavingBalance { get; set; }
    }
}
