//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOneFinancialManagerMK2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Goal
    {
        public int Id { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Description { get; set; }
        public Nullable<double> SavedAmount { get; set; }
        public Nullable<int> AccountID { get; set; }
    }
}
