//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CodeOneFinancialManagerMK2
{
    using System;
    using System.Collections.Generic;
    
    public partial class IFTT
    {
        public int Id { get; set; }
        public Nullable<int> AccountID { get; set; }
        public Nullable<int> ActionID { get; set; }
        public Nullable<double> CurrentAmount { get; set; }
        public Nullable<double> TriggerAmount { get; set; }
        public Nullable<int> MCC { get; set; }
        public Nullable<int> TimeFrameID { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<int> TriggerID { get; set; }
    }
}
